<?php


include_once 'layout.php';

echo "<div class='container'> ";

echo "<h1> Inheritance </h1>";


//class Person{
//    public $name;
//    public function callingPerson(){
//        echo "I am a person";}
//}
//class Student extends Person{  # extends ---->
//    public $level;
//    public function callingStudent(){
//        echo "<br>I am a person";}
//}
//
//$s = new Student();
//var_dump($s);
//
//## inheritance ---> is a relationship
//
//var_dump($s instanceof  Student);
//var_dump($s instanceof Person);
////
//$s->callingPerson();
//$s->callingStudent();

##### inheritance and constructor



//class Person{
//    public $name;
//    public function callingPerson(){
//        echo "I am a person";}
//
//    function __construct(){
//        echo "<h3 style='color: green'> Person constructor called </h3>";
//    }
//}
//class Student extends Person{  # extends ---->
//    public $level;
//    public function callingStudent(){
//        echo "<br>I am a person";}
//    function __construct(){
//        echo "<h3 style='color: red'> Student constructor called </h3>";
//    }
//
//}
//
//$s = new Student();
//var_dump($s);

## inheritance ---> is a relationship

//var_dump($s instanceof  Student);
//var_dump($s instanceof Person);
////
//$s->callingPerson();
//$s->callingStudent();
//
//

#########################################


//class Person{
//    public $name;
//    public function callingPerson(){
//        echo "I am a person";}
//
//    function __construct($name){
//        $this->name = $name;
//        echo "<h3 style='color: green'> Person constructor called </h3>";
//    }
//}
//class Student extends Person{  # extends ---->
//    public $level;
//    public function callingStudent(){
//        echo "<br>I am a person";}
//    function __construct($name){
//        # you may need to call the parent constructor
//        parent::__construct($name);
//        echo "<h3 style='color: red'> Student constructor called </h3>";
//    }
//
//    function callingPerson($message="")
//    {
//        parent::callingPerson();// TODO: Change the autogenerated stub
//        print("<br>modified in the child, {$message}");
//    }
//
//}
//
//$s = new Student("Sondos");
//var_dump($s);
//
//$s->callingPerson();

##### overriding : ---> Inheritance relation --- ?
## 2 classes Parent , child --> function parent ,,, child

##################### Final keyword###########################

class Machine{
    public $brand;
    function sayHello(){
        echo "hello I am a machine";
    }
}
class Transportation extends Machine{
    public $type;
    final function canMove(){
        echo "I can move";
    }
}

final class Car extends Transportation {
    public $model;
    function sayHello()
    {
        parent::sayHello();
// TODO: Change the autogenerated stub
        echo "Called from the Car class";
    }


}

## You cannot inherit from final class.


















